project_id = "qjnppcfbywfazwolfppo"

[functions.sitemap]
verify_jwt = false

[functions.publish-scheduled-articles]
verify_jwt = false

[functions.publish-scheduled-flash-news]
verify_jwt = false

[functions.sync-matches]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.rss-feed]
verify_jwt = false

[functions.translate]
verify_jwt = false

[functions.football-api]
verify_jwt = false
